(() => {
  const data=window.DASHBOARD_DATA, $=s=>document.querySelector(s), profiles=$('#profiles'),nav=$('#navList'),stats=$('#stats'),rings=$('#rings'),focus=$('#focusContent'),tabs=$('#tabs'),upcoming=$('#upcomingList'),modal=$('#modal'),toast=$('#toast');let activeProfile=data.profiles[0],activeTab='Parenting Insight',toastTimer;
  function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
  function showModal(title,body,eyebrow='Celestial Rhythm'){ $('#modalTitle').textContent=title;$('#modalEyebrow').textContent=eyebrow;$('#modalBody').innerHTML=body;modal.showModal() }
  profiles.innerHTML=data.profiles.map((p,i)=>`<button class="profile-item ${i===0?'active':''}" data-profile="${p.name}" aria-pressed="${i===0}"><span class="profile-face" aria-hidden="true">${p.face}</span><span><span class="profile-name">${p.name}</span><br><span class="profile-meta">${p.sign} · Age ${p.age}</span></span></button>`).join('');
  profiles.addEventListener('click',e=>{const b=e.target.closest('[data-profile]');if(!b)return;activeProfile=data.profiles.find(p=>p.name===b.dataset.profile);profiles.querySelectorAll('.profile-item').forEach(x=>{const on=x===b;x.classList.toggle('active',on);x.setAttribute('aria-pressed',on)});showToast(`${activeProfile.name}’s parenting insight is now selected.`);if(activeTab==='Child Insight')renderFocus()});
  nav.innerHTML=data.navigation.map(([name,icon],i)=>`<button class="nav-link ${i===0?'active':''}" data-page="${name}" ${i===0?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span><span>${name}</span></button>`).join('');
  nav.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(!b)return;setNav(b.dataset.page)});document.querySelector('.settings-link').addEventListener('click',()=>setNav('Settings'));
  function setNav(page){document.querySelectorAll('.nav-link').forEach(b=>{const on=b.dataset.page===page;b.classList.toggle('active',on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});if(page==='Today'){document.querySelector('#today').scrollIntoView({behavior:'smooth'});return}const descriptions={Planner:'Your family calendar has a gentle morning routine, outdoor time, and evening wind-down planned for today.', 'Relational Dynamics':`Emma and Mia are both looking for consistency today. Try one-on-one check-ins and keep transitions predictable.`,Timeline:'Today’s rhythm: morning grounding, an unhurried afternoon, and a quiet evening routine.', 'Chart & Profile':'Your family chart brings together Taurus steadiness and Scorpio depth. Explore each child’s profile for more tailored guidance.',Journal:'Your journal is ready for today’s memories and small wins.', 'About Astrology':'Astrology can be a thoughtful lens for noticing patterns and opening conversations. Use these reflections as gentle prompts.',Settings:'Manage family profiles, reminders, and your dashboard preferences.'};showModal(page,`<p>${descriptions[page]||'Here is a little more about your family’s daily rhythm.'}</p><p><strong>Today’s prompt:</strong> What helped everyone feel safe, seen, and connected?</p>`,'Your family dashboard');closeSidebar()}
  stats.innerHTML=data.stats.map(s=>`<button class="stat-card" data-detail="${s.label}"><span><span class="stat-label">${s.label}</span><br><span class="stat-value">${s.value}</span></span><span class="stat-icon" style="background:${s.tone}" aria-hidden="true">${s.icon}</span></button>`).join('');stats.addEventListener('click',e=>{const b=e.target.closest('[data-detail]');if(!b)return;const item=data.stats.find(s=>s.label===b.dataset.detail);showModal(item.label,`<p>${item.detail}</p><p>Use this as a gentle guide for your family’s day.</p>`) });
  rings.innerHTML=data.rings.map(r=>`<article class="ring-card"><div class="ring-label"><span aria-hidden="true">${r.icon}</span>${r.label}</div><div class="ring" style="--percent:${r.percent};--tone:${r.tone}" role="img" aria-label="${r.label}: ${r.label==='Mood'?'calm':r.value}"><strong>${r.value}</strong></div><div class="ring-state">${r.state}</div><div class="ring-note">${r.note}</div></article>`).join('');
  const tabNames=['Parenting Insight','Active Transits','Child Insight'];tabs.innerHTML=tabNames.map((n,i)=>`<button class="tab-button" role="tab" aria-selected="${i===0}" data-tab="${n}">${n}</button>`).join('');tabs.addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;activeTab=b.dataset.tab;tabs.querySelectorAll('[role=tab]').forEach(t=>t.setAttribute('aria-selected',t===b));renderFocus()});
  function renderFocus(){if(activeTab==='Parenting Insight'){focus.innerHTML=`<div class="focus-head"><div class="eyebrow">Today’s parenting focus</div></div><div class="focus-grid">${data.focus.map(f=>`<article class="focus-item"><span class="small-icon" aria-hidden="true">${f.icon}</span><div><h3>${f.title}</h3><ul>${f.items.map(x=>`<li>${x}</li>`).join('')}</ul></div></article>`).join('')}</div><div class="eyebrow subheading">Suggestions for today</div><div class="suggestion-grid">${data.suggestions.map(s=>`<article class="suggestion" tabindex="0" role="button" data-suggestion="${s.title}"><span class="small-icon" aria-hidden="true">${s.icon}</span><div><h3>${s.title}</h3><p>${s.text}</p></div></article>`).join('')}</div>`}else if(activeTab==='Active Transits'){focus.innerHTML=`<div class="eyebrow">Today’s planetary weather</div><h2 style="font:600 22px var(--serif);margin:8px 0 14px">Three transits shaping your day</h2><div class="suggestion-grid">${[['☿','Mercury trine Moon','A good window for patient conversation and naming feelings.'],['♀','Venus in Cancer','Offer comfort through closeness, familiar meals, and home rituals.'],['♄','Saturn sextile Sun','Keep expectations clear and routines reassuring.']].map(x=>`<article class="suggestion"><span class="small-icon">${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join('')}</div>`}else{focus.innerHTML=`<div class="eyebrow">${activeProfile.name} · ${activeProfile.sign} · Age ${activeProfile.age}</div><h2 style="font:600 22px var(--serif);margin:8px 0 14px">A little insight for ${activeProfile.name.split(' ')[0]}</h2><div class="suggestion-grid"><article class="suggestion"><span class="small-icon">☼</span><div><h3>What may help</h3><p>${activeProfile.name.split(' ')[0]} may feel most settled with familiar rhythms, warm encouragement, and a little room to move at their own pace.</p></div></article><article class="suggestion"><span class="small-icon">♡</span><div><h3>Try together</h3><p>Share a quiet moment outdoors. Ask one open question and give them time to answer in their own way.</p></div></article></div>`}}
  focus.addEventListener('click',e=>{const c=e.target.closest('[data-suggestion]');if(c)showModal(c.dataset.suggestion,`<p>${data.suggestions.find(s=>s.title===c.dataset.suggestion)?.text||'Make space for a gentle, connected moment together.'}</p><p><strong>Try it today:</strong> Keep it simple and follow your child’s pace.</p>`,'A gentle suggestion')});focus.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-suggestion]')){e.preventDefault();e.target.click()}});renderFocus();
  upcoming.innerHTML=data.events.map(ev=>`<button class="event-row" data-event="${ev.name}" aria-label="${ev.name}, ${ev.date}, in ${ev.count}"><span class="event-icon" aria-hidden="true">${ev.icon}</span><span><span class="event-name">${ev.name}</span><br><span class="event-date">${ev.date}</span></span><span class="event-count">In ${ev.count}</span></button>`).join('');upcoming.addEventListener('click',e=>{const b=e.target.closest('[data-event]');if(b)showModal(b.dataset.event,`<p>${b.dataset.event} is coming up on ${data.events.find(ev=>ev.name===b.dataset.event).date}. A lovely moment to celebrate what makes your child feel special.</p><label for="reminder">Add a reminder note</label><input id="reminder" placeholder="A small idea to remember…" />`,'Family calendar')});$('#upcomingMore').addEventListener('click',()=>showModal('Family calendar','<p><strong>Jul 14</strong> — Emma’s 7th Birthday</p><p><strong>Aug 2</strong> — Solar Return for Mia</p><p><strong>Every day</strong> — Your family’s calm evening wind-down</p>','Upcoming moments'));
  $('#journalButton').addEventListener('click',()=>showModal('Write in your journal','<label for="journalMood">How did today feel?</label><input id="journalMood" placeholder="Calm, busy, joyful…" /><label for="journalNote">A moment you want to remember</label><textarea id="journalNote" placeholder="Write a few words about today…"></textarea><label><input id="journalSave" type="checkbox" style="width:auto;margin:0 7px 0 0" /> Save this note on this device</label>','Quick journal'));
  $('#addChild').addEventListener('click',()=>showModal('Add a child','<label for="childName">Child’s name</label><input id="childName" placeholder="Name" required /><label for="childBirth">Birthday</label><input id="childBirth" type="date" /><p>Your child’s profile will appear here in this demo.</p>','Family profile'));
  $('#modal').addEventListener('click',e=>{if(e.target===modal)modal.close()});$('#modal').addEventListener('close',()=>{const name=$('#childName')?.value?.trim();if(name){showToast(`${name}’s profile details are ready to add.`)}if($('#journalSave')?.checked){const note=$('#journalNote')?.value?.trim();if(note){try{localStorage.setItem('celestial-journal',JSON.stringify({mood:$('#journalMood').value,note,date:new Date().toISOString()}))}catch{}showToast('Your journal note is saved on this device.')}}});
  $('#notifications').addEventListener('click',()=>showModal('You’re all caught up','<p>No new notifications. We’ll let you know when a family milestone is coming up.</p>','Notifications'));$('#profileMenu').addEventListener('click',()=>showModal('Your account','<p>Welcome to Celestial Rhythm, Jamie.</p><p>Family profiles: Emma and Mia</p><p>Daily reminder: 8:00 AM</p>','Account'));
  $('#themeToggle').addEventListener('click',e=>{const isDark=document.body.classList.toggle('dark');e.currentTarget.setAttribute('aria-pressed',isDark);try{localStorage.setItem('celestial-theme',isDark?'dark':'light')}catch{}});try{if(localStorage.getItem('celestial-theme')==='dark'){document.body.classList.add('dark');$('#themeToggle').setAttribute('aria-pressed','true')}}catch{}
  const sidebar=$('#sidebar'),menu=$('#menuToggle');function closeSidebar(){sidebar.classList.remove('open');menu.setAttribute('aria-expanded','false')}menu.addEventListener('click',()=>{const open=sidebar.classList.toggle('open');menu.setAttribute('aria-expanded',open)});document.addEventListener('click',e=>{if(sidebar.classList.contains('open')&&!sidebar.contains(e.target)&&e.target!==menu)closeSidebar()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSidebar()});
  const date=new Date();$('#dateLabel').textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(date);
})();

